account.prompt=So tai khoan: 
account.error=So tai khoan phai la 1 so va phai co 10 chu so
password.prompt=Mat khau: 
password.error=Mat khau phai trong khoang 8-31 ky tu va phai chua ky tu va so
captcha.prompt=Captcha: 
captcha.input=Nhap 1 ky tu captcha: 
captcha.error=Captcha sai
